---
title: "ABM_analysis"
author: "SKK"
date: "2023-05-25"
output: html_document
---

# Investigate ABM

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(tidyverse,
               here,
               network,
               igraph,
               ggraph,
               tidygraph,
               patchwork)
```

## Table of content


```{r Load data}
stat <- tibble(expand.grid(iteration = seq(1,100),
                           table = seq(1,3),
                           network = seq(1,2)))
stat <- stat %>% 
  mutate(
                           pre_post = rep(vector("list", length = 600)),
                           degree = NA,
                           degree_mean = NA,
                           degree_dist = NA,
                           transitivity = NA,
                           between = NA,
                           eigen_cen = NA
                           )
              
#rename 1:3 to long,round, square
for (row in 1:nrow(stat)){
stat$table[row] <- if (stat$table[row] == 1) "long" else if (stat$table[row] == 2) "round" else "square"
}

for (row in 1:nrow(stat)){
stat$network[row] <- if (stat$network[row] == 1) "pre" else "post" 
}

stat <- arrange(stat, iteration, table)

for (row in 1:nrow(df_collected)){
  #make network graphs
  temp <- df_collected[[3]][[row]]
  edges <- temp$ID
  nodes_pre <- df_collected[[4]][[row]] %>% filter(weight!=0)
  nodes_post <- df_collected[[5]][[row]] %>% filter(weight!=0)
  pre_igraph <- graph_from_data_frame(d = nodes_pre,
                        vertices = edges,
                        directed = TRUE)
  post_igraph <-
  graph_from_data_frame(d = nodes_post,
                        vertices = edges,
                        directed = TRUE)
  #save
  pre_index <- which(stat$iteration == df_collected$iteration[row] & stat$table == df_collected$table_type[row])[1]
  post_index <- which(stat$iteration == df_collected$iteration[row] & stat$table == df_collected$table_type[row])[2]
  #network graphs
  stat$pre_post[[pre_index]] <- pre_igraph#as_long_data_frame(pre_igraph, mode="all"))
  stat$pre_post[[post_index]] <- post_igraph#as_long_data_frame(degree(post_igraph, mode="all"))
  #make degree
  stat$degree[[pre_index]] <- as.data.frame(degree(pre_igraph, mode="all"))
  stat$degree[[post_index]] <- as.data.frame(degree(post_igraph, mode="all"))
  #mean degree
  stat$degree_mean[[pre_index]] <- as.numeric(mean(degree(pre_igraph)))
  stat$degree_mean[[post_index]] <- as.numeric(mean(degree(post_igraph)))
  #degree distribution
  stat$degree_dist[[pre_index]] <- as.data.frame(degree_distribution(pre_igraph))
  stat$degree_dist[[post_index]] <- as.data.frame(degree_distribution(post_igraph))
  #transitivity
  stat$transitivity[[pre_index]] <- as.data.frame(transitivity(pre_igraph, type = 'local'))
  stat$transitivity[[post_index]] <- as.data.frame(transitivity(post_igraph, type = 'local'))
  #betweenness
  stat$between[[pre_index]] <- as.data.frame(betweenness(pre_igraph))
  stat$between[[post_index]] <- as.data.frame(betweenness(post_igraph))
  #eigen centrality
  stat$eigen_cen[[pre_index]] <- as.data.frame(eigen_centrality(pre_igraph)$vector)
  stat$eigen_cen[[post_index]] <- as.data.frame(eigen_centrality(post_igraph)$vector)
}

```

#Analyse
```{r STRAND}
library(devtools)
install_github("ctross/STRAND")
library(STRAND)
```

```{r trying network with matrix in stead}
strand_df <- strand_df %>% 
  mutate(table_type=as.factor(table_type))
temp <- df_collected[[3]][1][[1]]
IDs <- temp$ID

# Create an empty matrix with IDxID dimensions
exposure <- matrix(0, nrow = length(IDs), ncol = length(IDs), dimnames = list(IDs, IDs))

# Fill the matrix with the value 50
exposure[] <- 50

blocks = strand_df %>% select(table_type) %>% as.data.frame()
individual=df_collected[[3]][1][[1]] %>% select(c("ie","satisfaction_baseline","interest1","interest2","interest3","moves","n_closefriends"))

for (row in 1:nrow(strand_df)){
  #pre
  temp <- strand_df[[3]][row][[1]]
  strand_df[[3]][row][[1]] <- temp %>%
  pivot_wider(names_from = to, values_from = weight, values_fill = 0) %>%
  column_to_rownames(var = "from") %>%
  as.matrix()
  #post
  temp <- strand_df[[4]][row][[1]]
  strand_df[[4]][row][[1]] <- temp %>%
  pivot_wider(names_from = to, values_from = weight, values_fill = 0) %>%
  column_to_rownames(var = "from") %>%
  as.matrix()
  
}


```

```{r}
matrix <- m1[,1:64]

for (row in seq_len(nrow(matrix))) {
    weight <- matrix[row, col]
    
    # Create a new entry in the data list
    entry <- data.frame(from = row, to = col, weight = weight)
    entry <- data.frame(from = as.numeric(rownames(matrix)[row]), to = as.numeric(colnames(matrix)[col]), weight = weight)
    
    # Append the entry to the data list
    new_df <- rbind(new_df, entry)
    }
  }
}
new_df
```





## Mess

```{r}
par(mfrow=c(1,2))

mean(degree(pre_igraph))
mean(degree(post_igraph))
sd(degree(pre_igraph))

preD <- degree(pre_igraph)
postD <- degree(post_igraph) 

t.test(preD, postD)

mean(degree_distribution(pre_igraph))
mean(degree_distribution(post_igraph))

DegreeDistr_ABM <- degree_distribution(pre_igraph)
DegreeDistr_2019 <- degree_distribution(post_igraph)

t.test(DegreeDistr_ABM, DegreeDistr_2019)

# Degree

rethinking::dens(degree_distribution(pre_igraph))+
  title("ABM Degree Distribution")
rethinking::dens(degree_distribution(post_igraph))+
  title("2019 Data Degree Distribution")



# Average path length

mean_distance(pre_igraph, directed = TRUE, unconnected = TRUE)
mean_distance(post_igraph, directed = TRUE, unconnected = TRUE)

# Clustering coefficient

transitivity(pre_igraph)
transitivity(post_igraph)

Transitivity_ABM <- transitivity(pre_igraph, type = 'local')
Transitivity_2019 <-transitivity(post_igraph, type = 'local')

t.test(Transitivity_ABM, Transitivity_2019) 
## Centrality

mean(betweenness(pre_igraph))
rethinking::dens(betweenness(pre_igraph))+
  title("ABM Betweenness Centrality")
mean(betweenness(post_igraph))
rethinking::dens(betweenness(post_igraph))+
  title("2019 Data Betweenness Centrality")

Betweenness_ABM <- betweenness(pre_igraph)
Betweenness_2019 <- betweenness(post_igraph)

t.test(Betweenness_ABM, Betweenness_2019) 


mean(eigen_centrality(pre_igraph)$vector)
mean(eigen_centrality(post_igraph)$vector)

Eigen_ABM <- eigen_centrality(pre_igraph)$vector
Betweenness_2019 <- betweenness(post_igraph)

t.test(Eigen_ABM, Eigen_2019)


```



# 4 Community Detection

```{r}
#making the networks look the same for easier comparing
E(network_cleaned)$arrow.mode <- 0
V(network_cleaned)$label <- ""

# Community detection
wc1 <- cluster_walktrap(pre_igraph)
# wc1 <- cluster_infomap(as.undirected(network_cleaned))
modularity(wc1)
membership(wc1)

wc2 <- cluster_walktrap(post_igraph)
modularity(wc2)
membership(wc2)


par(mfrow=c(1,2))

plot(wc1, pre_igraph, layout = layout_nicely)
plot(wc2, post_igraph)


# Community detection (by optimizing modularity over partitions):
clp <- cluster_louvain(as.undirected(network_cleaned))
plot(clp, network_cleaned, layout = layout_nicely, edge.arrow.size = 0.2)


clp <- cluster_louvain(as.undirected(post_igraph))
plot(clp, post_igraph, layout = layout_nicely, edge.arrow.size = 0.2)


#clop <- cluster_optimal(post_igraph)
#plot(clop, post_igraph)

#par(mfrow=c(1,1))
```





```{r test hosts}
#check it out
# head(hosts)
#seems good

#could be fun to make a radar chart of the hosts
#https://www.datanovia.com/en/blog/beautiful-radar-chart-in-r-using-fmsb-and-ggplot-packages/
#opar <- par() 
# Define settings for plotting in a 3x4 grid, with appropriate margins:
#par(mar = rep(0.8,3))
#par(mfrow = c(3,3))
# Produce a radar-chart for each student
#for (i in 1:nrow(hosts)) {
 # radarchart(
  #  hosts[c(2:7, i), ],#hosts[ i,c(2:7)]
   # pfcol = c("#99999980",NA),
    #pcol= c(NA,2), plty = 1, plwd = 2,
#    title = row.names(hosts)[i]
 # )
#}
# Restore the standard par() settings
#par <- par(opar) 
```

```{r test interest overlap}
# par(mfrow=c(1,3))
# plot(density(hosts$interest1))
# plot(density(hosts$interest2))
# plot(density(hosts$interest3))
# #library(plyr)
# dplyr::count_(hosts, vars = c('interest1','interest2','interest3'))
# aggregate(ID ~ ., hosts, FUN = length)
# 
# dupes <- apply(hosts[,2:4], 1, function(x) any(duplicated(x)))
# dupes <- hosts[dupes, ]
# dup <- dupes[1,]
# stringr::str_count(dupes) #18 true #four characters, =28 procent had an overlap in at least two coloumns
```

```{r test interest overlap}
# #test if people have overlap in interests within themselves
# dupes <- apply(guests[,5:7], 1, function(x) any(duplicated(x)))
# stringr::str_count(dupes) #16 true #four characters, =25 procent had an overlap in at least two coloumns

```

```{r plot packages}
#Plotting Friendship network
pacman::p_load(tidyverse,
               here,
               network,
               igraph,
               ggraph,
               tidygraph,
               patchwork,
               bootnet)

```

```{r plot prenetwork}
pacman::p_load(tidyverse,
               here,
               network,
               igraph,
               ggraph,
               tidygraph,
               patchwork)
nodes <- party$ID

pre_igraph <-
  graph_from_data_frame(d = df_collected$pre_network[[1]],
                        vertices = nodes,
                        directed = TRUE)


pre_igraph <- simplify(pre_igraph, 
                                  remove.multiple = TRUE, 
                                  remove.loops = TRUE,
                                  edge.attr.comb = igraph_opt("edge.attr.comb"))



E(pre_igraph)$arrow.mode <- 0



V(pre_igraph)$label <- "" 

V(pre_igraph)$frame.color <- "white"
V(pre_igraph)$color <- "orange"
E(pre_igraph)$width <- edge_attr(pre_igraph)$weight/16 #this one adjusts the size of arrows 
#E(pre_igraph)$arrow.size <- 0.01
plot(pre_igraph,
     layout=layout_nicely,
     #vertex.label= V(pr,
     edge.arrow.size=0.01#,
     #vertex.label.color = "black",
     #vertex.size=node.size
     )

#ask Emma how to make their cool network plot
```

```{r plot network at round tables}
round <- expand.grid(from=round_tables$new_seat,to=round_tables$new_seat)
round$weight <- 0
round <- filter(round, from != to)
#Add weight to all the friendships we just created
for (i in 1:nrow(round_tables)){
  current_id <- round_tables$new_seat[i]
  temp <- round %>% filter(from==current_id)
   for (k in strsplit(round_tables$indices[i], ", ")[[1]]){
     temp2 <- temp %>% filter(to==k)
      temp2$weight <- temp2$weight + 1
       temp <- temp %>% filter(to!=k)
      temp <- rbind(temp2, temp)
  }
    round <- round %>% filter(from!=current_id)
    round <- rbind(round, temp)
}

# for visualisation
round <- round[!(round$weight==0),]
round_graph <-
  graph_from_data_frame(d = round,
                        vertices = round_tables$new_seat,
                        directed = TRUE)

plot(round_graph,
     layout = layout_nicely, # Explore layouts!
     edge.arrow.size = 0.2) 
```

```{r plot network at square tables}
square <- expand.grid(from=square_tables$new_seat,to=square_tables$new_seat)
square$weight <- 0
square <- filter(square, from != to)
#Add weight to all the friendships we just created
for (i in 1:nrow(square_tables)){
  current_id <- square_tables$new_seat[i]
  temp <- square %>% filter(from==current_id)
   for (k in strsplit(square_tables$indices[i], ", ")[[1]]){
     temp2 <- temp %>% filter(to==k)
      temp2$weight <- temp2$weight + 1
       temp <- temp %>% filter(to!=k)
      temp <- rbind(temp2, temp)
  }
    square <- square %>% filter(from!=current_id)
    square <- rbind(square, temp)
}

# for visualisation
square <- square[!(square$weight==0),]
square_graph <-
  graph_from_data_frame(d = square,
                        vertices = square_tables$new_seat,
                        directed = TRUE)

plot(square_graph,
     layout = layout_nicely, # Explore layouts!
     edge.arrow.size = 0.2) 
```

```{r plot network at long table}
long <- expand.grid(from=long_table$seat,to=long_table$seat)
long$weight <- 0
long <- filter(long, from != to)
#Add weight to all the friendships we just created
for (i in 1:nrow(long_table)){
  current_id <- long_table$seat[i]
  temp <- long %>% filter(from==current_id)
   for (k in strsplit(long_table$indices[i], ", ")[[1]]){
     temp2 <- temp %>% filter(to==k)
      temp2$weight <- temp2$weight + 1
       temp <- temp %>% filter(to!=k)
      temp <- rbind(temp2, temp)
  }
    long <- long %>% filter(from!=current_id)
    long <- rbind(long, temp)
}

# for visualisation
long <- long[!(long$weight==0),]
long_graph <-
  graph_from_data_frame(d = long,
                        vertices = long_table$seat,
                        directed = TRUE)

plot(long_graph,
     layout = layout_nicely, # Explore layouts!
     edge.arrow.size = 0.2) 

```

```{r plot post_network}
pacman::p_load(tidyverse,
               here,
               network,
               igraph,
               ggraph,
               tidygraph,
               patchwork)
nodes <- party$ID

post_igraph <-
  graph_from_data_frame(d =df_collected$post_network[[1]],
                        vertices = nodes,
                        directed = TRUE)


post_igraph <- simplify(post_igraph, 
                                  remove.multiple = TRUE, 
                                  remove.loops = TRUE,
                                  edge.attr.comb = igraph_opt("edge.attr.comb"))



E(post_igraph)$arrow.mode <- 0



V(post_igraph)$label <- "" 

V(post_igraph)$frame.color <- "white"
V(post_igraph)$color <- "orange"
E(post_igraph)$width <- edge_attr(post_igraph)$weight/16 #this one adjusts the size of arrows 
#E(post_igraph)$arrow.size <- 0.01
plot(post_igraph,
     layout=layout_nicely,
     #vertex.label= V(pr,
     edge.arrow.size=0.01#,
     #vertex.label.color = "black",
     #vertex.size=node.size
     )

#ask Emma how to make their cool network plot
``` 