---
title: "tryout_abm"
author: "SKK"
date: "2023-05-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r make hosts}
#to point out the hosts, so we can have interesser/relationer der overlapper med værten
iterations <- 8
n_people <- 64

n_hosts <- iterations+100 #have the number of hosts needed for running all interations *100 to make them identifiable as hosts
  
  hosts <- tibble(
    ID = 101:n_hosts, #*100 to give the hosts identifyable ID's
    #introvert / extrovert scale from 1-9, from Emma and Mie
     ie = sample(1:9, iterations, replace = TRUE, prob =  c(0.05, 0.15, 0.15, 0.1, 0.1, 0.15, 0.15, 0.1, 0.05)),
    # 
    # #the number does not really matter unless you want to make the network complecated...
     n_household = sample(1:8,iterations, replace =TRUE, prob = hus_prob), 
     n_closefriends = n_people, #friends with every one at the party
    # 
    #  #in the tryout markdown the randomization of interest was tested an only a few combination was shown twice, therefore we will not do anything further to randomize the selected interests.
     interest1 = sample(1:14, iterations, replace = TRUE, prob = int_prob),
     interest2 = sample(1:14, iterations, replace = TRUE, prob = int_prob),
     interest3 = sample(1:14, iterations, replace = TRUE, prob = int_prob)
  )
```

```{r test interest overlap}
par(mfrow=c(1,3))
plot(density(hosts$interest1))
plot(density(hosts$interest2))
plot(density(hosts$interest3))
library(plyr)
dplyr::count_(hosts, vars = c('interest1','interest2','interest3'))
aggregate(ID ~ ., hosts, FUN = length)

dupes <- apply(hosts[,2:4], 1, function(x) any(duplicated(x)))
dupes <- hosts[dupes, ]
dup <- dupes[1,]
stringr::str_count(dupes) #18 true #four characters, =28 procent had an overlap in at least two coloumns
```

```{r make people}
for (i in iterations){ #just to get a feel of how to set up people function
 host <- hosts[i,] #choose a host
}
host <- hosts[5,]
host_interest <- c(host$interest1,host$interest2,host$interest3)

uni_prob <- runif(n_people, min = 0, max = 100)
  
#function
  guests <- tibble(ID = 1:n_people,
                   #individual 
                   ie = sample(1:9, n_people, replace = TRUE, prob =  ie_prob),
                   n_household = sample(1:8, n_people, replace =TRUE, prob = hus_prob),
                   n_closefriends = sample(0:10, n_people, replace = TRUE, prob = ven_prob),
                  
                  interest1 = sample(host_interest,n_people,replace=TRUE), #choose a random interest that fits with the host
                  interest2 = sample(1:14, n_people, replace = TRUE, prob = int_prob),
                  interest3 = sample(1:14, n_people, replace = TRUE, prob = int_prob),
                  weight_time = round((runif(n_people, min = -1, max = 1)),digits = 2),#testing to make weights for the satisfaction rate
                  weight_interest = 1-abs(weight_time)#testing to make weight for the satisfaction rate
  )

#test if people have overlap in interests within themselves
dupes <- apply(guests[,5:7], 1, function(x) any(duplicated(x)))
stringr::str_count(dupes) #16 true #four characters, =25 procent had an overlap in at least two coloumns

```

```{r make selskab}
party <- rbind(host,guests) 
```

-- arbejder her--

```{r friends network}
party <- rbind(host,guests) 

party <- party %>% #add connection count to guests, the hosts is already full...
  mutate(max_friends = n_closefriends+1,
         current_n_connections = 0,
         missing_friends = max_friends-current_n_connections,
         n_closefriends=n_closefriends+1)

#step 2: connect everybody with everybody using their number of friends
#make lists of possible connections
for (id in seq(party$ID)){
  
  #friends time
  n_rows_friends = party$n_closefriends[[id]]
  row = party$ID[[id]]
  if (n_rows_friends == 0){next}
  df_temp_fri <-  tibble(expand.grid(ID=row,
                     p_friends = seq(n_rows_friends)
                     ))
  #save dataframe
  if (id == 1){
    df_fri <- df_temp_fri
  } else {
    df_fri <- rbind(df_fri,df_temp_fri)
  }
}

list_of_friends <- df_fri[,1] %>% 
  mutate(row=row.names(df_fri))


pre_network <-  tibble(from =NULL, to=NULL, weight=NULL)

list_of_friends_guest <- list_of_friends[66:553,]
#this loop makes the right number of connections, but NA occures for to coloumn after first run..., every second person is "satisfied" with friends in party dataframe...
for (person in list_of_friends_guest[["ID"]]){ #need for be done as many times as there are people on the list
  if (party$missing_friends[person] > 0){
    choosen = list_of_friends_guest[sample(1:nrow(list_of_friends_guest), 1), ]
    choosen_friend = choosen[["ID"]]
    connection = tibble(from   = guests[person,1],
                         to = guests[choosen_friend,1],
                         weight = 16)
    pre_network <- rbind(pre_network, connection)
    
    #remove from list
    #choosen
    row =as.numeric(choosen[["n"]])
    list_of_friends_guest <- list_of_friends_guest[-row,]
    #person
    #temp_rows=as.numeric(list_of_friends_guest$row[list_of_friends_guest$ID==person])
    #row = sample(temp_rows, 1)
    #list_of_friends_guest <- list_of_friends_guest[-row,]
    
    party$missing_friends[party$ID == person] <- party$missing_friends[party$ID == person] -1
    # party$missing_friends[party$ID == choosen_friend] <- party$missing_friends[party$ID == choosen_friend] -1

    
  }else if (party$missing_friends[person] == 0){next}
}


#this loop makes the right number of connections, but NA occures for to coloumn after first run..., every second person is "satisfied" with friends in party dataframe...
for (person in list_of_friends_guest[["ID"]]){ #need for be done as many times as there are people on the list
  if (party$missing_friends[person] > 0){
    choosen = list_of_friends_guest[sample(1:nrow(list_of_friends_guest), 1), ]
    repeat{
      
      
    }
    choosen_friend = choosen[["ID"]]
    connection = tibble(from   = guests[person,1],
                         to = guests[choosen_friend,1],
                         weight = 16)
    pre_network <- rbind(pre_network, connection)
    
    #remove from list
    row =as.numeric(choosen[["n"]])
    list_of_friends_guest <- list_of_friends_guest[-row,]
    
    party$missing_friends[party$ID == person] <- party$missing_friends[party$ID == person] -1

    
  }else if (party$missing_friends[person] == 0){next}
}

#this loop works but for all rows in the possible list of friends...
for (person in list_of_friends_guest[["ID"]]){ #need for be done as many times as there are people on the list
  if (party$missing_friends[person] > 0){
    choosen = list_of_friends_guest[sample(1:nrow(list_of_friends_guest), 1), ]
    choosen_friend = choosen[["ID"]]
    connection = tibble(from   = guests[person,1],
                         to = guests[choosen_friend,1],
                         weight = 16)
    pre_network <- rbind(pre_network, connection)
    
    #remove from list
    #row =as.numeric(choosen[["n"]])
    #list_of_friends_guest <- list_of_friends_guest[-row,]
    
    #party$missing_friends[party$ID == person] <- -1  
    
  }else if (party$missing_friends[person] > 0){next}
}


#this loop works but once for each person in unique(list_of_friends_guest)
for (person in unique(list_of_friends_guest[["ID"]])){ #need for be done as many times as there are people on the list
  if (party$missing_friends[person] > 0){
    choosen = list_of_friends_guest[sample(1:nrow(list_of_friends_guest), 1), ]
    choosen_friend = choosen[["ID"]]
    connection = tibble(from   = guests[person,1],
                         to = guests[choosen_friend,1],
                         weight = 16)
    pre_network <- rbind(pre_network, connection)
    
    #remove from list
    #row =as.numeric(choosen[["n"]])
    #list_of_friends_guest <- list_of_friends_guest[-row,]
    
    #party$missing_friends[party$ID == person] <- -1  
    
  }else if (party$missing_friends[person] > 0){next}
}

#loop that worked yesterday but only made one connection per guest
for (person in unique(list_of_friends[["ID"]])){ #need for be done as many times as there are people on the list
  if (guests$missing_friends[person] > 0){
    if (nrow(list_friends) > 0){}
    choosen = list_of_friends[sample(1:nrow(list_of_friends), 1), ]
    choosen_friend = choosen[["ID"]]
    connection <- tibble(to = guests[choosen_friend,1],
                         from   = guests[person,1],
                         weight = 16)
    pre_network <- rbind(pre_network, connection)
    
    #remove from list
    row =as.numeric(choosen[["n"]])
    list_of_friends <- list_of_friends[-row,]
    
    guests$missing_friends[guests$ID == person] <- -1  
    
  }
}

#test if it worked
n_connections_needed <-   guests$n_closefriends
pre_network <- pre_network %>% 
  mutate(to=as.numeric(to))
n_connections_have <- xtabs(~pre_network$to)
n_connections <- tibble(nedded =n_connections_needed,
                        have =n_connections_have)
duplicated(n_connections) #all false....
```

```{r network}

#empty networks
friends <- tibble(to=NA,from=NA,weight=NA)

families <- tibble(to=NA,from=NA,weight=NA)


#make lists of possible connections
for (id in seq(party$ID)){
  
  #family
  if (party$n_household[[id]] == 1){ #people who have no family
    break
  } else {
  n_rows_family = party$n_household[[id]]
  df_temp_fam <-  tibble(expand.grid(ID=unique(id),
                     p_familiy = seq(n_rows_family)
                     ))
  }
  #save dataframe
  if (id == 1){
    df_fam <- df_temp_fam
  } else {
    df_fam <- rbind(df_fam,df_temp_fam)
  }
  
  #friends time
  n_rows_friends = party$n_closefriends[[id]] 
  df_temp_fri <-  tibble(expand.grid(ID=unique(id),
                     p_friends = seq(n_rows_friends)
                     ))
  #save dataframe
  if (id == 1){
    df_fri <- df_temp_fri
  } else {
    df_fri <- rbind(df_fri,df_temp_fri)
  }
}

list_of_friends <- df_fri[,1]
list_of_family <- df_fam[,1]

#reorder
  fam_dec <- party[order(-party$n_household),]
  #remove people who live alone
  fam_dec <- fam_dec[!(fam_dec$n_household == 1),]
  
#make families
for (people in nrow(fam_dec)){
  #setup count handler
  n_people <- 1
  max = fam_dec$n_household[[n_people]] 
  n_relatives <- 2
  person <- n_people+1

  repeat{
  while (n_relatives <= max){
    n_relatives <- 1+n_relatives
    #row             #to                #from             #weight
                   #the person at hand
    connection <- tibble(to=fam_dec[n_people,1], from=fam_dec[person,1],weight= 33 )
    
    #add to dataframe
    families <- rbind(families, connection)
    
    #add to counters
    n_relatives= +1
    person = +1
    if (n_relatives> max){next}
  } 
  n_people = +1 #move to next person
  max = fam_dec$n_household[[n_people]] #set new max
  #see if it already has been filled
  test <- xtabs(~from,families)
  n_relatives <- test[[n_people]][1]
  if (n_people > nrow(fam_dec)){break}
} 
}

  
  
  
  

  
#chatgpt
library(igraph)

# create an empty graph
edges <- NULL
g <- graph(edges = edges)

# add vertices to the graph
vertex_names <- unique(party$ID)
V(g)$name <- vertex_names

# add edges to the graph based on n_friends and n_family
for (i in 1:nrow(party)) {
  # get the source and target nodes
  source_node <- party[i, "ID"]
  target_node <- sample(vertex_names, party[i, "n_closefriends"] + party[i, "n_household"], replace = FALSE)
  
  # check if the target node is not the source node and if there is no existing edge
  for (j in target_node) {
    if (j != source_node && !edge.between(g, source_node, j)) {
      # determine the weight based on whether it's a friend or family
      if (j %in% sample(party[party$ID == source_node, "n_closefriends"], party[i, "n_closefriends"], replace = FALSE)) {
        weight <- 16
      } else {
        weight <- 33
      }
      # add the edge to the graph
      g <- add_edge(g, source_node, j, weight = weight)
    }
  }
}













#make friends clusters from interest... nooo
# normalize the n_family and n_friends values
df_norm <- as.data.frame(scale(party[, c("n_family", "n_friends")]))

# perform k-means clustering
set.seed(123) # for reproducibility
k <-  # number of clusters
kmeans_model <- kmeans(df_norm, centers = k)

# add cluster information to original dataframe
df$cluster <- as.factor(kmeans_model$cluster)




pre_party_network <-  tibble(expand.grid(ID=seq(unique(party$ID)),
                                         p_closefriends = seq(party$n_closefriends),
                                         p_familiy = seq(party$n_household)
                                         )
                              ) #%>% 
         # mutate(ID=ifelse(diagnosis=='td',ID+n*2,ID))
# group by ID and calculate the number of rows for each ID
aggregate(ID ~ n_closefriends, data = party, FUN = length)
aggregate(ID ~ n_household, data = party, FUN = length)

for (id in seq(party$ID)){
  
  n_rows_family = party$n_household[[id]]
  n_rows_friends= party$n_closefriends[[id]] 
  
  df_temp_fam <-  tibble(expand.grid(ID=unique(id),
                     p_familiy = seq(n_rows_family)
                     ))
  df_temp_fri <-  tibble(expand.grid(ID=unique(id),
                     p_friends = seq(n_rows_friends)
                     ))
  #save dataframe
  if (id == 1){
    df_fam <- df_temp_fam
    df_fri <- df_temp_fri
  } else {
    df_fam <- rbind(df_fam,df_temp_fam)
    df_fri <- rbind(df_fri,df_temp_fri)
  }
}#as long as it is just a foor loop no return needed
#dataframe structure: to from weight. weight: one weight added everytime they meet a total of 16 weights can be added, family nodes are made to start at 33 (at the end of party ranching from 33-49), friends nodes start at 16 (at the end of party ranching from 16-32)... arbitrary choice at the moment,

```

```{r people}
#to point out the hosts, so we can have interesser/relationer der overlapper med værten
iterations <- 8

n_hosts <- iterations+100 #have the number of hosts needed for running all interations *100 to make them identifiable as hosts
  
  hosts <- tibble(
    ID = 101:n_hosts, #*100 to give the hosts identifyable ID's
    #introvert / extrovert scale from 1-9, from Emma and Mie
     ie = sample(1:9, iterations, replace = TRUE, prob =  c(0.05, 0.15, 0.15, 0.1, 0.1, 0.15, 0.15, 0.1, 0.05)),
    # 
    # #the number does not really matter unless you want to make the network complecated...
     n_household = sample(1:8,iterations, replace =TRUE, prob = hus_prob), 
     n_closefriends = sample(0:10, iterations, replace = TRUE, prob = ven_prob), 
    # 
    #  #in the tryout markdown the randomization of interest was tested an only a few combination was shown twice, therefore we will not do anything further to randomize the selected interests.
     interest1 = sample(1:14, iterations, replace = TRUE, prob = int_prob),
     interest2 = sample(1:14, iterations, replace = TRUE, prob = int_prob),
     interest3 = sample(1:14, iterations, replace = TRUE, prob = int_prob)
  )

 host <- hosts[6,] #choose a host

  #decide host interest
   host_interest <- c(host$interest1,host$interest2,host$interest3)

   #make people
   people <- tibble(
     #individual
     ID = 1:n_people, 
     ie = sample(1:9, n_people, replace = TRUE, prob =  c(0.05, 0.15, 0.15, 0.1, 0.1, 0.15, 0.15, 0.1, 0.05)),
     n_household = sample(1:8, n_people, replace =TRUE, prob = hus_prob),
     n_closefriends = sample(0:10, n_people, replace = TRUE, prob = ven_prob),
     
     #interests based on the selected host
     interest1 = sample(host_interest,n_people,replace=TRUE), #choose a random interest that fits with the host
     interest2 = sample(1:14, n_people, replace = TRUE, prob = int_prob),
     interest3 = sample(1:14, n_people, replace = TRUE, prob = int_prob)
     )


party <- rbind(host,people) 
```

```{r tables}
#make round + square tables
n_tables <- 8
n_seats <- 8

#round
round_table <- tibble(expand_grid(TableNo = seq(n_tables), SeatNo = seq(n_seats),ContactSeatNo=seq(2)))
round_table <- round_table %>% mutate(ContactSeatNo=NA)#cleaning out the arbitrary numbers
#square
square_table <- tibble(expand_grid(TableNo = seq(n_tables), SeatNo = seq(n_seats),ContactSeatNo=seq(5)))
square_table <- square_table %>% mutate(ContactSeatNo=NA)#cleaning out the arbitrary numbers
#long
long_table <- tibble(expand_grid(TableNo=1,SeatNo=seq(n_people),ContactSeatNo=seq(5)))
long_table <- long_table[-c(4,5,9,10,314,315,319,320),] #remove edges partners as they do not exists.
long_table <- long_table %>% mutate(ContactSeatNo=NA)#cleaning out the arbitrary numbers

#input the seatno with the current seatno can make contact with in the contactseatno
#round

#square
list1 <- c(1,2,3,4,5,6)
list2 <- c(7,8,9,10,11,12)
list3 <- c(13,14,15,16,17,18)
list_try <- rbind(list1,list2,list3)

df1 = data.frame(
  y1 = c(1, 2, 3),
  y2 = c(4, 5, 6)
)
 
# Create another dataframe
df2 = data.frame(
  y1 = c(7, 8, 9),
  y2 = c(1, 4, 6)
)
try <- as.numeric(c("1","2","3","4","5","6"))
try <- c(1,2,3,4,5,6)
test <- tibble(ID=1,tester=NA)
test$tester <- list(try) #the current condition of the firneds_id

pacman::p_load('stringi')
stri_paste(unlist(test$tester), collapse='')
tryout <- toString(test$tester, sep='""')
 
# Creating a list of data frames
# by naming all its components
listOfDataframe = list(
  "Dataframe1" = df1,
  "Dataframe2" = df2
)
print(listOfDataframe)


#long_
long_try <-  data.frame(table = NA, seat = NA, contact_seats = NA)
# Loop through each table and seat
for (table in 1:n_tables) {
  for (seat in 1:n_seats) {
    # Calculate the indices for the contact seats
    indices <- c(seat - 2, seat - 1, seat, seat + 1, seat + 2)
    
    # Remove any indices that are out of bounds
    indices <- indices[indices >= 1 & indices <= n_seats]
    
    # Create a new row for each contact seat
    for (contact_seat in indices) {
      long_temp <- data.frame(table = table, seat = seat, contact_seats = contact_seat)
      
      # Append the row to the dataframe
      long_try <- rbind(long_try, long_temp)
    }
  }
}

#adding who can talk to who
#in network form or how?
  ggrg 
```