---
title: "tryout_abm"
author: "SKK"
date: "2023-05-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#devtools::install_github("ricardo-bion/ggradar")
pacman::p_load(tidyverse
#, ggplot2, gridExtra, fmsb,ggradar
)

```

```{r}
###Define variables from literature###
setwd('.')
load("prob.RData")

ie_prob <- c(0.05, 0.15, 0.15, 0.10, 0.10, 0.15, 0.15, 0.10, 0.05) #Introvert/extrovert prob on scale from 1 - 10. From Emma and Mie
int_prob <- c(0.955, 0.955, 0.435, 0.645, 0.625, 0.545, 0.390, 0.325, 0.845, 0.750, 0.320, 0.355, 0.250, 0.215) #Interest probabilities. 14 different interests taken from Statistikbanken.
ven_prob <- c(0.01, 0.02, 0.05, 0.08, 0.12, 0.20, 0.10, 0.04, 0.06, 0.02, 0.30) #Probabilities of having different number of friends. Taken from Vive paper
household_prob <-c(0.3970565,0.333184,0.1130965,0.1074418, 0.03661024,0.008320509, 0.002352696, 0.001937746) # Number of people in your household probability

###Define model variables ###

iterations <- 8 #How many times do we want to run the model?
n_people <- 64 #How many people are at a party?

```


```{r make hosts}
### Define hosts of parties ###

# All host shares at least 1 interest with everyone, and are connected to all guests

max_hosts <- iterations+100 #define the highest host id (+100 to make hosts identifiable)
  
hosts <- tibble(
    ID = 101:max_hosts, #+100 to give the hosts identifyable ID's
    ie = sample(1:9, iterations, replace = TRUE, prob =  ie_prob),    #introvert / extrovert scale from 1-9, from Emma and Mie
    n_household = sample(1:8,iterations, replace =TRUE, prob = household_prob), #Number of people in your household
    n_closefriends = n_people-1, #friends with every one at the party
    #in the tryout markdown the randomization of interest was tested an only a few combination was shown twice, therefore we will not do anything further to randomize the selected interests.
    interest1 = sample(1:14, iterations, replace = TRUE, prob = int_prob),
    interest2 = sample(1:14, iterations, replace = TRUE, prob = int_prob),
    interest3 = sample(1:14, iterations, replace = TRUE, prob = int_prob),
    weight_time = round((runif(iterations, min = -1, max = 1)),digits = 2),#testing to make weights for the satisfaction rate
    weight_interest = 1-abs(weight_time)#testing to make weight for the satisfaction rate
  )
``` 
  
```{r test hosts}
#check it out
head(hosts)
#seems good

#could be fun to make a radar chart of the hosts
#https://www.datanovia.com/en/blog/beautiful-radar-chart-in-r-using-fmsb-and-ggplot-packages/
#opar <- par() 
# Define settings for plotting in a 3x4 grid, with appropriate margins:
#par(mar = rep(0.8,3))
#par(mfrow = c(3,3))
# Produce a radar-chart for each student
#for (i in 1:nrow(hosts)) {
 # radarchart(
  #  hosts[c(2:7, i), ],#hosts[ i,c(2:7)]
   # pfcol = c("#99999980",NA),
    #pcol= c(NA,2), plty = 1, plwd = 2,
#    title = row.names(hosts)[i]
 # )
#}
# Restore the standard par() settings
#par <- par(opar) 
```

```{r test interest overlap}
par(mfrow=c(1,3))
plot(density(hosts$interest1))
plot(density(hosts$interest2))
plot(density(hosts$interest3))
#library(plyr)
dplyr::count_(hosts, vars = c('interest1','interest2','interest3'))
aggregate(ID ~ ., hosts, FUN = length)

dupes <- apply(hosts[,2:4], 1, function(x) any(duplicated(x)))
dupes <- hosts[dupes, ]
dup <- dupes[1,]
stringr::str_count(dupes) #18 true #four characters, =28 procent had an overlap in at least two coloumns
```

```{r setup people for party}
### Choosing who the guests are at all parties

# for (i in iterations){ #just to get a feel of how to set up people function
#  host <- hosts[i,] #choose a host
# }

i = 5

host <- hosts[i,]
host_interest <- c(host$interest1,host$interest2,host$interest3)

#Assigning variables to guests 
guests <- tibble(ID = 2:n_people-1, #Creating 63 people
                  ie = sample(1:9, n_people-1, replace = TRUE, prob =  ie_prob), #Introvert/extrovert values to people

                  n_household = sample(1:8, n_people-1, replace =TRUE, prob = household_prob), #Amount of people in household
                  n_closefriends = sample(1:10, n_people-1, replace = TRUE, prob = ven_prob[1:10]), #Amount of close friends (everyone has at least one friend (the host))
                 
                  interest1 = sample(host_interest,n_people-1,replace=TRUE), #choose a random interest that fits with the host
                  interest2 = sample(1:14, n_people-1, replace = TRUE, prob = int_prob),
                  interest3 = sample(1:14, n_people-1, replace = TRUE, prob = int_prob),
                 
                  weight_time = round((runif(n_people-1, min = -1, max = 1)),digits = 2),#testing to make weights for the satisfaction rate
                  weight_interest = 1-abs(weight_time)#testing to make weight for the satisfaction rate
)
```
  
```{r make party}
party <- rbind(host,guests)
```


```{r test interest overlap}
#test if people have overlap in interests within themselves
dupes <- apply(guests[,5:7], 1, function(x) any(duplicated(x)))
stringr::str_count(dupes) #16 true #four characters, =25 procent had an overlap in at least two coloumns

```


```{r friends network}
party <- party %>% #add connection count to guests, the hosts is already full...
  mutate(max_friends = n_closefriends+1,
         current_n_connections = 0,
         missing_friends = max_friends-current_n_connections
         friend_ids = NA)

#a full network of all people with zero connection weights
pre_network <- expand.grid(from=party$ID,to=party$ID)
pre_network$weight <- 0
pre_network <- filter(pre_network, from != to)

# Iterate over each row in the dataframe
for (i in 1:nrow(party)) {
  num_friends <- party$n_closefriends[i]  # Get the number of friends for the current person
  id_pool <- party$ID[-i]  # Exclude the current person's ID from the pool of potential friends
  
  ids_above_100 <- id_pool[id_pool > 100]
  ids_below_100 <- id_pool[id_pool <= 100]
  
  # If the current person needs to have friends below 100
  if (num_friends >= 1) {
    # Add all IDs above 100 as friends
    friend_ids_above_100 <- ids_above_100
    remaining_friends <- num_friends - 1
    
    # Randomly select additional friend IDs from below 100
    friend_ids_below_100 <- sample(ids_below_100, size = remaining_friends, replace = FALSE)
    
    # Combine the friend IDs
    friend_ids <- c(friend_ids_above_100, friend_ids_below_100)
  } else {
    # Randomly select friend IDs from above 100
    friend_ids <- sample(ids_above_100, size = num_friends, replace = FALSE)
  }

  # Assign the selected friend IDs to the corresponding row in the dataframe
  party$friend_id[i] <- list(as.character(friend_ids))
}
```



```{r trying network with matrix in stead}
matrix <- base::matrix(0, nrow = n_people, ncol = n_people)	
matrix <- as.data.frame(matrix)
rownames(matrix) <- as.character(party$ID)
colnames(matrix) <- as.character(party$ID)
# make a for loop that loops through nrow(party) and assigns a weight of 16 to the friend in the matrix
for (i in 1:nrow(party)) {
  x <-  as.numeric(rownames(matrix)[i])
  
  friend_ids <- party$friend_id[i]  # split the string into individual IDs
  
  for (k in 1:length(friend_ids[[1]])) {
    y <- as.numeric(friend_ids[[1]][k])
     # Check if indices i and j are within the valid range
    if (i <= nrow(matrix) &&  y<= ncol(matrix)) {
      matrix[paste(x), paste(y)] <- 16
    }
  }
}
matrix

```

```{r}
matrix <- m1[,1:64]
```



```{r trying network with matrix in stead}	
#collapse matrix into a dataframe with from, to and weight
new_df <- data.frame(from = numeric(),
                     to = numeric(),
                     weight = numeric()
                     )

# Iterate over each row and column in the matrix
data_list <- list()
for (row in seq_len(nrow(matrix))) {
  for (col in 1:ncol(matrix)) {
    # Extract the weight value from the matrix
    if (matrix[row, col]!= 0 &&  row != col) {
    weight <- matrix[row, col]
    
    # Create a new entry in the data list
    entry <- data.frame(from = as.numeric(rownames(matrix)[row]), to = as.numeric(colnames(matrix)[col]), weight = weight)
    
    # Append the entry to the data list
    new_df <- rbind(new_df, entry)
    }
  }
}
new_df
```





--- mess --- måske er der noget godt der nede...

```{r friends network}
guests$friends <- map(guests$missing_friends, function(x) sample(guests$ID, x, replace = FALSE), )

pre_network %>% filter(from==105)

#step 2: connect everybody with everybody using their number of friends
#make lists of possible connections
for (id in seq(guests$ID)){
  
  
  #friends time
  n_rows_friends = guests$n_closefriends[[id]]
  row = guests$ID[[id]]
  if (n_rows_friends == 0){next}
  df_temp_fri <-  tibble(expand.grid(ID=row,
                     p_friends = seq(n_rows_friends)
                     ))
  #save dataframe
  if (id == 1){
    df_fri <- df_temp_fri
  } else {
    df_fri <- rbind(df_fri,df_temp_fri)
  }
}

list_of_friends <- df_fri[,1] %>% 
  mutate(row=row.names(df_fri))



pre_network <-  tibble(from =NULL, to=NULL, weight=NULL)

list_of_friends_guest <- list_of_friends[66:553,]
#this loop makes the right number of connections, but NA occures for to coloumn after first run..., every second person is "satisfied" with friends in party dataframe...
for (person in list_of_friends_guest[["ID"]]){ #need for be done as many times as there are people on the list
  if (party$missing_friends[person] > 0){
    choosen = list_of_friends_guest[sample(1:nrow(list_of_friends_guest), 1), ]
    choosen_friend = choosen[["ID"]]
    connection = tibble(from   = guests[person,1],
                         to = guests[choosen_friend,1],
                         weight = 16)
    pre_network <- rbind(pre_network, connection)
    
    #remove from list
    #choosen
    row =as.numeric(choosen[["n"]])
    list_of_friends_guest <- list_of_friends_guest[-row,]
    #person
    temp_rows=as.numeric(list_of_friends_guest$row[list_of_friends_guest$ID==person])
    row = sample(temp_rows, 1)
    list_of_friends_guest <- list_of_friends_guest[-row,]
    
    party$missing_friends[party$ID == person] <- party$missing_friends[party$ID == person] -1
    # party$missing_friends[party$ID == choosen_friend] <- party$missing_friends[party$ID == choosen_friend] -1

    
  }else if (party$missing_friends[person] == 0){next}
}


#this loop makes the right number of connections, but NA occures for to coloumn after first run..., every second person is "satisfied" with friends in party dataframe...
for (person in list_of_friends_guest[["ID"]]){ #need for be done as many times as there are people on the list
  if (party$missing_friends[person] > 0){
    choosen = list_of_friends_guest[sample(1:nrow(list_of_friends_guest), 1), ]
    repeat{
      
      
    }
    choosen_friend = choosen[["ID"]]
    connection = tibble(from   = guests[person,1],
                         to = guests[choosen_friend,1],
                         weight = 16)
    pre_network <- rbind(pre_network, connection)
    
    #remove from list
    row =as.numeric(choosen[["n"]])
    list_of_friends_guest <- list_of_friends_guest[-row,]
    
    party$missing_friends[party$ID == person] <- party$missing_friends[party$ID == person] -1

    
  }else if (party$missing_friends[person] == 0){next}
}

#this loop works but for all rows in the possible list of friends...
for (person in list_of_friends_guest[["ID"]]){ #need for be done as many times as there are people on the list
  if (party$missing_friends[person] > 0){
    choosen = list_of_friends_guest[sample(1:nrow(list_of_friends_guest), 1), ]
    choosen_friend = choosen[["ID"]]
    connection = tibble(from   = guests[person,1],
                         to = guests[choosen_friend,1],
                         weight = 16)
    pre_network <- rbind(pre_network, connection)
    
    #remove from list
    #row =as.numeric(choosen[["n"]])
    #list_of_friends_guest <- list_of_friends_guest[-row,]
    
    #party$missing_friends[party$ID == person] <- -1  
    
  }else if (party$missing_friends[person] > 0){next}
}


#this loop works but once for each person in unique(list_of_friends_guest)
for (person in unique(list_of_friends_guest[["ID"]])){ #need for be done as many times as there are people on the list
  if (party$missing_friends[person] > 0){
    choosen = list_of_friends_guest[sample(1:nrow(list_of_friends_guest), 1), ]
    choosen_friend = choosen[["ID"]]
    connection = tibble(from   = guests[person,1],
                         to = guests[choosen_friend,1],
                         weight = 16)
    pre_network <- rbind(pre_network, connection)
    
    #remove from list
    #row =as.numeric(choosen[["n"]])
    #list_of_friends_guest <- list_of_friends_guest[-row,]
    
    #party$missing_friends[party$ID == person] <- -1  
    
  }else if (party$missing_friends[person] > 0){next}
}

#loop that worked yesterday but only made one connection per guest
for (person in unique(list_of_friends[["ID"]])){ #need for be done as many times as there are people on the list
  if (guests$missing_friends[person] > 0){
    if (nrow(list_friends) > 0){}
    choosen = list_of_friends[sample(1:nrow(list_of_friends), 1), ]
    choosen_friend = choosen[["ID"]]
    connection <- tibble(to = guests[choosen_friend,1],
                         from   = guests[person,1],
                         weight = 16)
    pre_network <- rbind(pre_network, connection)
    
    #remove from list
    row =as.numeric(choosen[["n"]])
    list_of_friends <- list_of_friends[-row,]
    
    guests$missing_friends[guests$ID == person] <- -1  
    
  }
}

#test if it worked
n_connections_needed <-   guests$n_closefriends
pre_network <- pre_network %>% 
  mutate(to=as.numeric(to))
n_connections_have <- xtabs(~pre_network$to)
n_connections <- tibble(nedded =n_connections_needed,
                        have =n_connections_have)
duplicated(n_connections) #all false....
```

```{r network}

#empty networks
friends <- tibble(to=NA,from=NA,weight=NA)

families <- tibble(to=NA,from=NA,weight=NA)


#make lists of possible connections
for (id in seq(party$ID)){
  
  #family
  if (party$n_household[[id]] == 1){ #people who have no family
    break
  } else {
  n_rows_family = party$n_household[[id]]
  df_temp_fam <-  tibble(expand.grid(ID=unique(id),
                     p_familiy = seq(n_rows_family)
                     ))
  }
  #save dataframe
  if (id == 1){
    df_fam <- df_temp_fam
  } else {
    df_fam <- rbind(df_fam,df_temp_fam)
  }
  
  #friends time
  n_rows_friends = party$n_closefriends[[id]] 
  df_temp_fri <-  tibble(expand.grid(ID=unique(id),
                     p_friends = seq(n_rows_friends)
                     ))
  #save dataframe
  if (id == 1){
    df_fri <- df_temp_fri
  } else {
    df_fri <- rbind(df_fri,df_temp_fri)
  }
}

list_of_friends <- df_fri[,1]
list_of_family <- df_fam[,1]

#reorder
  fam_dec <- party[order(-party$n_household),]
  #remove people who live alone
  fam_dec <- fam_dec[!(fam_dec$n_household == 1),]
  
#make families
for (people in nrow(fam_dec)){
  #setup count handler
  n_people <- 1
  max = fam_dec$n_household[[n_people]] 
  n_relatives <- 2
  person <- n_people+1

  repeat{
  while (n_relatives <= max){
    n_relatives <- 1+n_relatives
    #row             #to                #from             #weight
                   #the person at hand
    connection <- tibble(to=fam_dec[n_people,1], from=fam_dec[person,1],weight= 33 )
    
    #add to dataframe
    families <- rbind(families, connection)
    
    #add to counters
    n_relatives= +1
    person = +1
    if (n_relatives> max){next}
  } 
  n_people = +1 #move to next person
  max = fam_dec$n_household[[n_people]] #set new max
  #see if it already has been filled
  test <- xtabs(~from,families)
  n_relatives <- test[[n_people]][1]
  if (n_people > nrow(fam_dec)){break}
} 
}

  
  
  
  

  
#chatgpt
library(igraph)

# create an empty graph
edges <- NULL
g <- graph(edges = edges)

# add vertices to the graph
vertex_names <- unique(party$ID)
V(g)$name <- vertex_names

# add edges to the graph based on n_friends and n_family
for (i in 1:nrow(party)) {
  # get the source and target nodes
  source_node <- party[i, "ID"]
  target_node <- sample(vertex_names, party[i, "n_closefriends"] + party[i, "n_household"], replace = FALSE)
  
  # check if the target node is not the source node and if there is no existing edge
  for (j in target_node) {
    if (j != source_node && !edge.between(g, source_node, j)) {
      # determine the weight based on whether it's a friend or family
      if (j %in% sample(party[party$ID == source_node, "n_closefriends"], party[i, "n_closefriends"], replace = FALSE)) {
        weight <- 16
      } else {
        weight <- 33
      }
      # add the edge to the graph
      g <- add_edge(g, source_node, j, weight = weight)
    }
  }
}













#make friends clusters from interest... nooo
# normalize the n_family and n_friends values
df_norm <- as.data.frame(scale(party[, c("n_family", "n_friends")]))

# perform k-means clustering
set.seed(123) # for reproducibility
k <-  # number of clusters
kmeans_model <- kmeans(df_norm, centers = k)

# add cluster information to original dataframe
df$cluster <- as.factor(kmeans_model$cluster)




pre_party_network <-  tibble(expand.grid(ID=seq(unique(party$ID)),
                                         p_closefriends = seq(party$n_closefriends),
                                         p_familiy = seq(party$n_household)
                                         )
                              ) #%>% 
         # mutate(ID=ifelse(diagnosis=='td',ID+n*2,ID))
# group by ID and calculate the number of rows for each ID
aggregate(ID ~ n_closefriends, data = party, FUN = length)
aggregate(ID ~ n_household, data = party, FUN = length)

for (id in seq(party$ID)){
  
  n_rows_family = party$n_household[[id]]
  n_rows_friends= party$n_closefriends[[id]] 
  
  df_temp_fam <-  tibble(expand.grid(ID=unique(id),
                     p_familiy = seq(n_rows_family)
                     ))
  df_temp_fri <-  tibble(expand.grid(ID=unique(id),
                     p_friends = seq(n_rows_friends)
                     ))
  #save dataframe
  if (id == 1){
    df_fam <- df_temp_fam
    df_fri <- df_temp_fri
  } else {
    df_fam <- rbind(df_fam,df_temp_fam)
    df_fri <- rbind(df_fri,df_temp_fri)
  }
}#as long as it is just a foor loop no return needed
#dataframe structure: to from weight. weight: one weight added everytime they meet a total of 16 weights can be added, family nodes are made to start at 33 (at the end of party ranching from 33-49), friends nodes start at 16 (at the end of party ranching from 16-32)... arbitrary choice at the moment,

```
```{r people}
#to point out the hosts, so we can have interesser/relationer der overlapper med værten
iterations <- 8

n_hosts <- iterations+100 #have the number of hosts needed for running all interations *100 to make them identifiable as hosts
  
  hosts <- tibble(
    ID = 101:n_hosts, #*100 to give the hosts identifyable ID's
    #introvert / extrovert scale from 1-9, from Emma and Mie
     ie = sample(1:9, iterations, replace = TRUE, prob =  c(0.05, 0.15, 0.15, 0.1, 0.1, 0.15, 0.15, 0.1, 0.05)),
    # 
    # #the number does not really matter unless you want to make the network complecated...
     n_household = sample(1:8,iterations, replace =TRUE, prob = hus_prob), 
     n_closefriends = sample(0:10, iterations, replace = TRUE, prob = ven_prob), 
    # 
    #  #in the tryout markdown the randomization of interest was tested an only a few combination was shown twice, therefore we will not do anything further to randomize the selected interests.
     interest1 = sample(1:14, iterations, replace = TRUE, prob = int_prob),
     interest2 = sample(1:14, iterations, replace = TRUE, prob = int_prob),
     interest3 = sample(1:14, iterations, replace = TRUE, prob = int_prob)
  )

 host <- hosts[6,] #choose a host

  #decide host interest
   host_interest <- c(host$interest1,host$interest2,host$interest3)

   #make people
   people <- tibble(
     #individual
     ID = 1:n_people, 
     ie = sample(1:9, n_people, replace = TRUE, prob =  c(0.05, 0.15, 0.15, 0.1, 0.1, 0.15, 0.15, 0.1, 0.05)),
     n_household = sample(1:8, n_people, replace =TRUE, prob = hus_prob),
     n_closefriends = sample(0:10, n_people, replace = TRUE, prob = ven_prob),
     
     #interests based on the selected host
     interest1 = sample(host_interest,n_people,replace=TRUE), #choose a random interest that fits with the host
     interest2 = sample(1:14, n_people, replace = TRUE, prob = int_prob),
     interest3 = sample(1:14, n_people, replace = TRUE, prob = int_prob)
     )


party <- rbind(host,people) 
```
